syntax = "proto3";

package docker.v1;

option go_package = "github.com/Szent7/medovukha-web/api/docker/v1;dockerpb";

service DockerService {
  //containers
  rpc GetContainerList(Empty) returns (ListContainerBaseInfo);
  rpc PauseContainerByID(BaseID) returns (BaseResponse);
  rpc UnpauseContainerByID(BaseID) returns (BaseResponse);
  rpc KillContainerByID(BaseID) returns (BaseResponse);
  rpc StartContainerByID(BaseID) returns (BaseResponse);
  rpc StopContainerByID(BaseID) returns (BaseResponse);
  rpc RestartContainerByID(BaseID) returns (BaseResponse);
  rpc RemoveContainerByID(BaseID) returns (BaseResponse);

  //images
  rpc GetImageList(Empty) returns (ListImageBaseInfo);

  //networks
  rpc GetNetworkList(Empty) returns (ListNetworkBaseInfo);

  //volumes
  rpc GetVolumeList(Empty) returns (ListVolumeBaseInfo);

  //deploy
  rpc CreateFromGit(DeployFromGit) returns (BaseResponse);

  //events
  rpc GetContainerState(Empty) returns (stream ContainerState);
}

//common
message Empty {}

message BaseID {
  string id = 1;
}

message BaseResponse {
  string message = 1;
}

//containers
message Port {
  string ip = 1;
  uint32 private_port = 2; //uint16
  uint32 public_port = 3; //uint16
  string type = 4;
}

message ListContainerBaseInfo {
  repeated ContainerBaseInfo items = 1;
}

message ContainerBaseInfo {
  string id = 1;
  repeated string names = 2;
  string image_name = 3;
  repeated Port ports = 4;
  int64 created = 5;
  string state = 6;
}

//images
message ListImageBaseInfo {
  repeated ImageBaseInfo items = 1;
}

message ImageBaseInfo {
  string id = 1;
  repeated string tags = 2;
  int64 size = 3;
  int64 created = 4;
}

//networks
message ListNetworkBaseInfo {
  repeated NetworkBaseInfo items = 1;
}

message NetworkBaseInfo {
  string name = 1;
  string id = 2;
  string driver = 3;
  bool enable_ipv6 = 4;
  string ipam_driver = 5;
  repeated string subnet = 6;
  repeated string gateway = 7;
  bool attachable = 8;
  bool docker_network = 9;
}

//volumes
message ListVolumeBaseInfo {
  repeated VolumeBaseInfo items = 1;
}

message VolumeBaseInfo {
  string name = 1;
  string driver = 2;
  string mountpoint = 3;
  string created = 4;
}

//deploy
message DeployFromGit {
  string url = 1;
  string dockerfile = 2;
  string docker_compose = 3;
  string docker_run = 4;
}

//events
message ContainerState {
  string type = 1;
  string action = 2;
  Actor actor = 3;
}

message Actor {
  string id = 1;
  map<string, string> attributes = 2;
}
